---
- hosts: node1
  remote_user: root
  become: yes
  become_user: root
  roles:
      - common
      - { role: elasticsearch, es_instance_name: "{{ hostname }}.{{ domain_name }}", es_heap_size: "1g", es_data_dirs: "/opt/elasticsearch",
    es_config: {
        cluster.name: "{{ cluster_name }}",
        network.host: {{ node1_ip }},
        discovery.zen.ping.unicast.hosts: "{{ hostname }}.{{ domain_name }}:9300,{{ hostname }}.{{ domain_name }}:9300,{{ hostname }}.{{ domain_name }}.it:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        discovery.zen.minimum_master_nodes: 3,
        gateway.recover_after_nodes: 3,
        gateway.expected_nodes: 4,
        gateway.recover_after_time: 15m,
        node.data: true,
        node.master: true,
        bootstrap.mlockall: false,
        discovery.zen.ping.multicast.enabled: false }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: centos
    es_plugins:
     - plugin: elasticsearch/license
       version: latest

- hosts: node2
  remote_user: root
  become: yes
  become_user: root
  roles:
      - common
      - { role: elasticsearch, es_instance_name: "{{ hostname }}.{{ domain_name }}", es_heap_size: "1g", es_data_dirs: "/opt/elasticsearch", 
    es_config: {
        discovery.zen.ping.unicast.hosts: "{{ hostname }}.{{ domain_name }}:9300,{{ hostname }}.{{ domain_name }}:9300,{{ hostname }}.{{ domain_name }}:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: true,
        bootstrap.mlockall: false,
        cluster.name: "{{ cluster_name }}",
        network.host: {{ node2_ip }},
        discovery.zen.minimum_master_nodes: 3,
        gateway.recover_after_nodes: 3,
        gateway.expected_nodes: 4,
        gateway.recover_after_time: 15m,
        discovery.zen.ping.multicast.enabled: false } 
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: centos
    es_plugins:
     - plugin: elasticsearch/license
       version: latest

- hosts: node3
  remote_user: root
  become: yes
  become_user: root
  roles:
      - common
      - { role: elasticsearch, es_instance_name: "{{ hostname }}.{{ domain_name }}", es_heap_size: "1g", es_data_dirs: "/opt/elasticsearch",
    es_config: {
        discovery.zen.ping.unicast.hosts: "{{ hostname }}.{{ domain_name }}:9300,{{ hostname }}.{{ domain_name }}:9300,{{ hostname }}.{{ domain_name }}:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: true,
        bootstrap.mlockall: false,
        cluster.name: "{{ cluster_name }}",
        network.host: {{ node3_ip }},
        discovery.zen.minimum_master_nodes: 3,
        gateway.recover_after_nodes: 3,
        gateway.expected_nodes: 4,
        gateway.recover_after_time: 15m,
        discovery.zen.ping.multicast.enabled: false } 
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: centos
    es_plugins:
     - plugin: elasticsearch/license
       version: latest

- hosts: node4
  remote_user: root
  become: yes
  become_user: root
  roles:
      - common
      - { role: elasticsearch, es_instance_name: "{{ hostname }}.{{ domain_name }}", es_heap_size: "1g", es_data_dirs: "/opt/elasticsearch",
    es_config: {
        discovery.zen.ping.unicast.hosts: "{{ hostname }}.{{ domain_name }}:9300,{{ hostname }}.{{ domain_name }}:9300,{{ hostname }}.{{ domain_name }}:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: true,
        bootstrap.mlockall: false,
        cluster.name: "{{ cluster_name }}",
        network.host: {{ node4_ip }},
        discovery.zen.minimum_master_nodes: 3,
        gateway.recover_after_nodes: 3,
        gateway.expected_nodes: 4,
        gateway.recover_after_time: 15m,
        discovery.zen.ping.multicast.enabled: false }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: centos
    es_plugins:
     - plugin: elasticsearch/license
       version: latest

